// 橙築選物 — 商品資料 (mock)
// 30+ 件商品，涵蓋家電、生活選物、居家用品

const PRODUCTS = [
  // === 家電 KINYO ===
  {
    id: "ar-2018",
    name: "KINYO 12L 微電腦氣炸鍋",
    cat: "家電",
    catKey: "appliance",
    price: 2680,
    origPrice: 3680,
    badge: "熱銷",
    stock: 32,
    sold: 1247,
    rating: 4.8,
    reviewCount: 326,
    color: "#F5C09A",
    accent: "#E58A4F",
    icon: "🔥",
    desc: "12L 大容量、無油健康、微電腦控溫，全家份量一鍋搞定。",
    features: ["12L 大容量", "60-200°C 控溫", "8 種預設模式", "可拆洗炸籃"],
    flash: true,
  },
  {
    id: "kim-21w",
    name: "KINYO 不鏽鋼真空保溫杯 500ml",
    cat: "家電",
    catKey: "appliance",
    price: 580,
    origPrice: 880,
    badge: "新品",
    stock: 88,
    sold: 432,
    rating: 4.7,
    reviewCount: 124,
    color: "#D9E2EC",
    accent: "#5B7C99",
    icon: "🥤",
    desc: "316 醫療級不鏽鋼，6 小時保溫保冷，輕量便攜。",
    features: ["316 不鏽鋼", "6hr 保溫", "500ml", "防漏設計"],
  },
  {
    id: "kde-2330",
    name: "KINYO 雙效除濕電暖器",
    cat: "家電",
    catKey: "appliance",
    price: 1980,
    origPrice: 2480,
    stock: 14,
    sold: 289,
    rating: 4.6,
    reviewCount: 87,
    color: "#FFE2C7",
    accent: "#D97A3A",
    icon: "♨️",
    desc: "暖風 + 除濕雙模式，台灣冬天潮濕剋星。",
    features: ["雙效合一", "1200W", "傾倒斷電", "靜音運轉"],
  },
  {
    id: "kfd-3060",
    name: "KINYO 直立式無線吸塵器",
    cat: "家電",
    catKey: "appliance",
    price: 3280,
    origPrice: 4580,
    badge: "熱銷",
    stock: 7,
    sold: 968,
    rating: 4.9,
    reviewCount: 245,
    color: "#FFD2D2",
    accent: "#E54848",
    icon: "🧹",
    desc: "120W 強力吸力、HEPA 濾網、續航 35 分鐘。",
    features: ["120W 吸力", "HEPA 濾網", "35 分鐘續航", "1.2kg 輕量"],
    flash: true,
  },
  {
    id: "kf-7710",
    name: "KINYO 12 吋遙控立扇",
    cat: "家電",
    catKey: "appliance",
    price: 1280,
    stock: 45,
    sold: 178,
    rating: 4.5,
    reviewCount: 56,
    color: "#E0F0E8",
    accent: "#4A8E6C",
    icon: "💨",
    desc: "DC 直流馬達、12 段風速、夜間模式超靜音。",
    features: ["DC 馬達", "12 段風速", "遙控操作", "8 小時定時"],
  },
  {
    id: "khh-9590",
    name: "KINYO 即熱式飲水機",
    cat: "家電",
    catKey: "appliance",
    price: 2480,
    origPrice: 2980,
    badge: "新品",
    stock: 28,
    sold: 92,
    rating: 4.7,
    reviewCount: 31,
    color: "#D6E8F5",
    accent: "#3B7BC7",
    icon: "💧",
    desc: "3 秒即熱、5 段水溫、4L 大水箱。",
    features: ["3 秒即熱", "5 段水溫", "4L 水箱", "兒童鎖"],
  },

  // === 生活選物 ===
  {
    id: "lf-mug",
    name: "日式手作陶瓷馬克杯 (一對)",
    cat: "生活",
    catKey: "lifestyle",
    price: 880,
    stock: 22,
    sold: 156,
    rating: 4.9,
    reviewCount: 78,
    color: "#F2EAE0",
    accent: "#A88860",
    icon: "☕",
    desc: "京都職人手作，每個都是獨一無二的釉色變化。",
    features: ["手作陶瓷", "300ml", "微波可用", "禮盒包裝"],
  },
  {
    id: "lf-towel",
    name: "今治認證純棉浴巾組",
    cat: "生活",
    catKey: "lifestyle",
    price: 1480,
    origPrice: 1980,
    badge: "熱銷",
    stock: 18,
    sold: 423,
    rating: 4.8,
    reviewCount: 142,
    color: "#F5F0E8",
    accent: "#8C9E8E",
    icon: "🛁",
    desc: "日本今治毛巾，極致蓬鬆吸水，越洗越柔軟。",
    features: ["今治認證", "100% 純棉", "70x140cm", "禮盒裝"],
  },
  {
    id: "lf-diffuser",
    name: "天然精油擴香組",
    cat: "生活",
    catKey: "lifestyle",
    price: 980,
    stock: 35,
    sold: 234,
    rating: 4.7,
    reviewCount: 89,
    color: "#EDE4F0",
    accent: "#8E6B9E",
    icon: "🌿",
    desc: "薰衣草、佛手柑、雪松三款香調可選。",
    features: ["天然精油", "150ml", "藤條擴香", "持續 60 天"],
    flash: true,
  },
  {
    id: "lf-candle",
    name: "大豆蠟手工香氛蠟燭",
    cat: "生活",
    catKey: "lifestyle",
    price: 680,
    stock: 42,
    sold: 312,
    rating: 4.6,
    reviewCount: 98,
    color: "#FFF0DB",
    accent: "#C9924E",
    icon: "🕯️",
    desc: "100% 大豆蠟、棉質燭芯、燃燒 40 小時。",
    features: ["大豆蠟", "棉質燭芯", "40hr 燃燒", "玻璃容器"],
  },
  {
    id: "lf-tea",
    name: "台灣高山茶禮盒組",
    cat: "生活",
    catKey: "lifestyle",
    price: 1880,
    origPrice: 2480,
    badge: "新品",
    stock: 16,
    sold: 67,
    rating: 4.9,
    reviewCount: 24,
    color: "#E5EDDB",
    accent: "#5C7C3C",
    icon: "🍵",
    desc: "阿里山烏龍 + 杉林溪烏龍，職人精選。",
    features: ["阿里山烏龍", "杉林溪烏龍", "150g x 2", "禮盒裝"],
  },
  {
    id: "lf-stationery",
    name: "Midori 黃銅文具組",
    cat: "生活",
    catKey: "lifestyle",
    price: 1280,
    stock: 25,
    sold: 134,
    rating: 4.8,
    reviewCount: 45,
    color: "#F5E8C7",
    accent: "#A88840",
    icon: "✒️",
    desc: "日本 Midori 黃銅尺、削筆器、迴紋針組合。",
    features: ["黃銅材質", "三件組", "禮盒裝", "日本製"],
  },

  // === 居家用品 ===
  {
    id: "hm-bedding",
    name: "天絲棉四件式床包組",
    cat: "居家",
    catKey: "home",
    price: 2680,
    origPrice: 3680,
    badge: "熱銷",
    stock: 12,
    sold: 287,
    rating: 4.7,
    reviewCount: 124,
    color: "#E8E4DC",
    accent: "#7C7268",
    icon: "🛏️",
    desc: "60 支天絲棉、親膚透氣、雙人加大 6x6.2 尺。",
    features: ["60 支天絲", "雙人加大", "親膚透氣", "四件組"],
  },
  {
    id: "hm-pillow",
    name: "記憶枕 (人體工學設計)",
    cat: "居家",
    catKey: "home",
    price: 980,
    stock: 38,
    sold: 412,
    rating: 4.6,
    reviewCount: 156,
    color: "#F0EAE2",
    accent: "#8C7E6E",
    icon: "💤",
    desc: "慢回彈記憶棉、人體工學弧度、可拆洗枕套。",
    features: ["慢回彈", "人體工學", "可拆洗", "防蟎抗菌"],
  },
  {
    id: "hm-rug",
    name: "北歐風幾何地毯 160x230cm",
    cat: "居家",
    catKey: "home",
    price: 2280,
    origPrice: 2980,
    stock: 9,
    sold: 89,
    rating: 4.7,
    reviewCount: 34,
    color: "#E8DCD2",
    accent: "#9E7C5C",
    icon: "🟫",
    desc: "土耳其進口、防滑底、可機洗。",
    features: ["土耳其製", "160x230cm", "防滑底", "可機洗"],
  },
  {
    id: "hm-storage",
    name: "無印風收納箱 (3 入組)",
    cat: "居家",
    catKey: "home",
    price: 780,
    stock: 56,
    sold: 245,
    rating: 4.5,
    reviewCount: 87,
    color: "#F5F0E8",
    accent: "#A89880",
    icon: "📦",
    desc: "PP 材質、可堆疊、附蓋子防塵。",
    features: ["PP 材質", "可堆疊", "三入組", "附蓋設計"],
  },
  {
    id: "hm-light",
    name: "落地閱讀燈 (LED 觸控)",
    cat: "居家",
    catKey: "home",
    price: 1880,
    origPrice: 2480,
    badge: "新品",
    stock: 21,
    sold: 76,
    rating: 4.8,
    reviewCount: 28,
    color: "#F0E8DC",
    accent: "#7C6852",
    icon: "💡",
    desc: "三段色溫、無極調光、護眼 LED。",
    features: ["三段色溫", "無極調光", "護眼 LED", "觸控操作"],
    flash: true,
  },
  {
    id: "hm-clock",
    name: "極簡靜音掛鐘",
    cat: "居家",
    catKey: "home",
    price: 580,
    stock: 64,
    sold: 198,
    rating: 4.6,
    reviewCount: 67,
    color: "#EAE4DC",
    accent: "#5C5048",
    icon: "🕰️",
    desc: "靜音機芯、北歐極簡設計、12 吋。",
    features: ["靜音機芯", "12 吋", "北歐設計", "鋁框"],
  },

  // === 更多家電 ===
  {
    id: "kj-blender",
    name: "KINYO 隨行杯果汁機",
    cat: "家電",
    catKey: "appliance",
    price: 880,
    origPrice: 1280,
    stock: 41,
    sold: 367,
    rating: 4.5,
    reviewCount: 102,
    color: "#FFE4D6",
    accent: "#E58A4F",
    icon: "🥤",
    desc: "USB 充電、無線設計、雙杯隨行。",
    features: ["USB 充電", "300ml x 2", "無線", "可拆洗"],
  },
  {
    id: "kc-coffee",
    name: "KINYO 半自動義式咖啡機",
    cat: "家電",
    catKey: "appliance",
    price: 4980,
    origPrice: 6580,
    badge: "熱銷",
    stock: 6,
    sold: 234,
    rating: 4.8,
    reviewCount: 89,
    color: "#E0D6C7",
    accent: "#6E5C44",
    icon: "☕",
    desc: "15 bar 高壓、奶泡器、雙杯萃取。",
    features: ["15 bar 高壓", "奶泡器", "雙杯萃取", "可拆水箱"],
    flash: true,
  },
  {
    id: "kt-toaster",
    name: "KINYO 復古多功能烤吐司機",
    cat: "家電",
    catKey: "appliance",
    price: 1480,
    stock: 28,
    sold: 145,
    rating: 4.6,
    reviewCount: 52,
    color: "#FFD8C7",
    accent: "#D97A3A",
    icon: "🍞",
    desc: "復古藍 / 米白 / 薄荷綠三色，6 段烤色。",
    features: ["6 段烤色", "復古設計", "三色可選", "防燙外殼"],
  },

  // === 更多生活 ===
  {
    id: "lf-soap",
    name: "馬賽手工皂禮盒組",
    cat: "生活",
    catKey: "lifestyle",
    price: 580,
    stock: 48,
    sold: 178,
    rating: 4.7,
    reviewCount: 64,
    color: "#F0EAE0",
    accent: "#9E8868",
    icon: "🧼",
    desc: "法國馬賽傳統工法、5 入禮盒。",
    features: ["馬賽傳統", "5 入組", "天然成分", "禮盒裝"],
  },
  {
    id: "lf-notebook",
    name: "MOLESKINE 筆記本",
    cat: "生活",
    catKey: "lifestyle",
    price: 780,
    stock: 35,
    sold: 234,
    rating: 4.8,
    reviewCount: 98,
    color: "#E5DCC7",
    accent: "#5C4838",
    icon: "📓",
    desc: "經典硬殼、象牙色內頁、附鬆緊帶。",
    features: ["硬殼裝幀", "240 頁", "鬆緊帶", "口袋設計"],
  },
  {
    id: "lf-wallet",
    name: "義大利植鞣革短夾",
    cat: "生活",
    catKey: "lifestyle",
    price: 2480,
    origPrice: 3280,
    badge: "新品",
    stock: 14,
    sold: 67,
    rating: 4.9,
    reviewCount: 23,
    color: "#E8D4C0",
    accent: "#8C5C3C",
    icon: "👛",
    desc: "義大利植鞣牛皮、職人手縫、6 卡位。",
    features: ["植鞣牛皮", "手縫工藝", "6 卡位", "RFID 防盜"],
  },

  // === 更多居家 ===
  {
    id: "hm-curtain",
    name: "遮光窗簾 (落地款)",
    cat: "居家",
    catKey: "home",
    price: 1280,
    stock: 32,
    sold: 156,
    rating: 4.5,
    reviewCount: 78,
    color: "#E8E0D6",
    accent: "#6E5E4E",
    icon: "🪟",
    desc: "85% 遮光、隔熱保溫、多色可選。",
    features: ["85% 遮光", "隔熱保溫", "可機洗", "多色"],
  },
  {
    id: "hm-mirror",
    name: "極簡圓形掛鏡 60cm",
    cat: "居家",
    catKey: "home",
    price: 1680,
    origPrice: 2180,
    stock: 18,
    sold: 92,
    rating: 4.7,
    reviewCount: 36,
    color: "#F0E8DC",
    accent: "#7C6852",
    icon: "🪞",
    desc: "黑色細邊框、防爆膜、附掛勾。",
    features: ["60cm 直徑", "防爆膜", "細邊框", "附掛勾"],
  },
  {
    id: "hm-vase",
    name: "玻璃花瓶兩件組",
    cat: "居家",
    catKey: "home",
    price: 880,
    stock: 27,
    sold: 134,
    rating: 4.6,
    reviewCount: 48,
    color: "#E0EAE5",
    accent: "#5C7C6C",
    icon: "🌸",
    desc: "手工吹製、大小兩入、北歐風。",
    features: ["手工吹製", "兩件組", "北歐風", "禮盒裝"],
  },
  {
    id: "hm-slipper",
    name: "記憶棉室內拖鞋",
    cat: "居家",
    catKey: "home",
    price: 480,
    stock: 78,
    sold: 412,
    rating: 4.7,
    reviewCount: 145,
    color: "#F5EAE0",
    accent: "#A88868",
    icon: "🥿",
    desc: "記憶棉鞋墊、止滑底、可機洗。",
    features: ["記憶棉", "止滑底", "可機洗", "多尺寸"],
  },
  {
    id: "hm-aroma",
    name: "竹製超音波加濕器",
    cat: "居家",
    catKey: "home",
    price: 1280,
    origPrice: 1680,
    stock: 24,
    sold: 178,
    rating: 4.6,
    reviewCount: 67,
    color: "#E8E0D2",
    accent: "#7C6E54",
    icon: "💨",
    desc: "300ml 容量、7 色夜燈、自動斷電。",
    features: ["300ml", "7 色夜燈", "自動斷電", "靜音運轉"],
  },
];

const CATEGORIES = [
  { key: "all", label: "全部商品", icon: "🛒" },
  { key: "appliance", label: "KINYO 家電", icon: "🏠" },
  { key: "lifestyle", label: "生活選物", icon: "✨" },
  { key: "home", label: "居家用品", icon: "🛋️" },
];

window.PRODUCTS = PRODUCTS;
window.CATEGORIES = CATEGORIES;
